import type { StringValue } from "ms";
import type { Secret } from "jsonwebtoken";
export const enviro = {
  port: process.env.PORT,
  nodeEnv: process.env.NODE_ENV as Secret,
  clientUrl: process.env.CLIENT_URL,
  dominUrl: process.env.DOMIN_URL,
  dbName: process.env.DB_NAME,
  dbUser: process.env.DB_USER,
  dbLocal: process.env.DB_LOCAL,
  dbPass: process.env.DB_PASS,
  mongoURL: process.env.ZONE_MONGODB_URI,
  jwtAccessToken: process.env.JWT_ACCESS_TOKEN as Secret,
  jwtAccessTTL: process.env.JWT_ACCESS_TTL as StringValue,
  jwtRefreshToken: process.env.JWT_REFRESH_TOKEN as Secret,
  jwtRefreshTTL: process.env.JWT_REFRESH_TTL as StringValue,
  jwtSecretCart: process.env.JWT_SECRET_CART as Secret,
  jwtCartTTL: process.env.JWT_CART_TTL as StringValue,
  jwtResetSecret: process.env.JWT_RESET_SECRET as Secret,
  jwtResetTTL: process.env.JWT_RESET_TTL as StringValue,
  genVerifyToken: process.env.GEN_VERIFY_TOKEN as StringValue,
  roundSalt: process.env.ROUND_SALT,
  emailHost: process.env.EMAIL_HOST,
  emailUser: process.env.EMAIL_USER,
  emailPass: process.env.EMAIL_PASS,
  emailPort: process.env.EMAIL_PORT,
  emailSecure: process.env.EMAIL_SECURE,
  emailFrom: process.env.EMAIL_FROM,
  stripeSecretKey: process.env.STRIPE_SECRET_KEY,
  cloudinaryApiCloudName: process.env.CLOUDINARY_API_CLOUD_NAME,
  cloudinaryApiKey: process.env.CLOUDINARY_API_KEY,
  cloudinaryApiSecretKey: process.env.CLOUDINARY_API_SECRET_KEY,
  cloudinaryApiUrl: process.env.CLOUDINARY_API_URL,
  webhookPassword: process.env.WEBHOOK_PASSWORD,
  vercelToken: process.env.VERCEL_TOKEN,
  vercelProjectId: process.env.VERCEL_PROJECTID,
  vercelTeamId: process.env.VERCEL_TEAM_ID,
  vercelApi: process.env.VERCEL_API,

  sessionSecret: process.env.JWT_SESSION_SECRET as StringValue,
};
